import Head from "next/head";
import MyImages from "@/components/MyImages";
import Overlap from "@/components/Infobar";
import Image from "next/image";
import Link from "next/link";
import bgImage from "images/filters_quality(85).webp";
import lemonImage from "images/filters_lemon(85).webp";
import svgLeft from "images/svg/svgexport-8.svg";
import leftLeaf from "images/svg/svgexport-5.svg";
import forest from "images/filters_quality(85) (2).webp";
import greenLemon from "images/filters_quality(85) (20).webp";
import AllImages from "@/components/AllImages";
import { useState } from "react";

export default function Home() {
  const [scrollTop, setScrollTop] = useState(0);

  const handleScroll = (e) => {
    setScrollTop(e.currentTarget.scrollTop);
  };

  return (
    <div>
      <Head>
        <title>Apeel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="relative w-full min-h-screen">
          <div className=" absolute bottom-6 -translate-y-1/2 mx-10 px-8 py-6">
            <p className="mb-6 text-sm text-offWhite">
              Longer-lasting produce.
            </p>
            <div>
              <h1 className=" mb-6 w-4/6 leading-14 text-offWhite text-5xl font-bold tracking-tighter">
                Plant-based protection
                <br /> that helps the produce you love stay fresh for longer.
              </h1>
            </div>
            <button className="px-6 py-3 rounded-3xl bg-offWhite">
              Find Apeel
            </button>
          </div>

          <MyImages
            src={bgImage}
            width={"100%"}
            className={"absolute -top-24 -z-10 w-full min-h-full"}
          />
        </div>

        {/* The yellow floting section */}
        <Overlap />

        <div className="relative w-full min-h-screen">
          {/* <MyImages src={lemonImage} fill className={"object-cover"} />
           */}

          <MyImages
            src={lemonImage}
            fill
            className={"absolute -z-10 -top-24 w-[100%] h-[120vh]"}
          />
          <div className="w-[100%] min-h-screen px-8 py-9 absolute flex lg:flex-row sm:flex-col">
            <div className="flex-1">
              <h1 className=" mb-0 w-full leading-14 text-offWhite text-7xl font-bold tracking-tighter">
                This Peel is
                <br /> Powerful
              </h1>
            </div>
            <div className="flex-1 flex items-end justify-end ">
              <div className="flex flex-col justify-end items-end ">
                <p className="w-1/2 mb-2 text-justify text-md leading-5 font-semibold text-offWhite">
                  Apeel keeps moisture inside the produce adn oxygen out,
                  dramatically slowing the rate that produce spoils. because we
                  use edible plant- based materials, we call it food protecting
                  your food.
                </p>

                <Link
                  href="/index"
                  className="w-1/2 flex items-center text-sm text-left leading-5 font-semibold text-offWhite"
                >
                  <p>How Apeel Works</p> <Image src={svgLeft} width={30} />
                </Link>
              </div>
            </div>
          </div>
        </div>

        <div className="flex justify-between text-my-green w-full min-h-screen rounded-xl">
          <div className="relative flex lg:flex-col justify-between flex-1 p-12 rounded-l-lg bg-offWhite">
            <h1 className="text-6xl w-100 font-extrabold">
              Seeing is
              <br /> believing.
            </h1>

            {/* <div className="flex-1">
            <Image src={avacardo} fill className="" />
            </div> */}

            <div className="text-center">Without Apeel</div>
          </div>
          <div className="relative flex lg:flex-col justify-between flex-1 p-12 rounded-r-lg bg-banana-400">
            <h1 className="text-6xl w-100 font-extrabold">.</h1>

            <div className="text-center">With Apeel</div>
          </div>
        </div>
        <section
          onScroll={handleScroll}
          className="scrolling-wrapper  px-8 bg-banana relative min-w-full min-h-screen overflow-y-hidden overflow-x-scroll"
        >
          {/* <Image src={leftLeaf} fill className=" absolute w-100 right-48" /> */}
          <div className="flex items-center">
            <div className="flex flex-col justify-between text-my-green flex-1 min-h-screen rounded-xl">
              <h1 className="flex-1 flex items-center justify-center text-7xl font-extrabold">
                Produce you <br /> love, protected by Apeel.
              </h1>
              <p>
                Discover our products, available in North America and Europe.
              </p>
            </div>

            <div className="flex-2">
              <AllImages />
            </div>
          </div>
        </section>

        <div className="relative w-full min-h-screen">
          {/* <MyImages src={lemonImage} fill className={"object-cover"} />
           */}

          <MyImages
            src={forest}
            fill
            className={"absolute -z-10 -top-24 w-[100%] h-[120vh]"}
          />
          <div className="w-[100%] min-h-screen px-8 py-9 flex">
            <div className=" flex-1 flex items-end justify-end ">
              <div className="flex flex-col justify-end items-end ">
                <h1 className="mb-8 w-2/3 leading-14 text-offWhite text-4xl font-bold tracking-tighter">
                  See the sustainability impact of
                  <br /> Apeel-Protected Produce.
                </h1>
                <p className="mb-8 w-2/3 mb-2 text-justify text-md leading-5 font-semibold text-offWhite">
                  Learn more about how preventing food waster helps to conserve
                  resources and avoid greenhouse gas emissions.
                </p>

                <Link
                  href="/index"
                  className="mb-8 w-2/3 flex items-center text-sm text-left leading-5 font-semibold text-offWhite"
                >
                  <p>Our Impact</p> <Image src={svgLeft} width={30} />
                </Link>
              </div>
            </div>
          </div>
        </div>

        <div className="overflow-hidden min-h-[90vh] w-full bg-cilantro">
          <div className="flex">
            <div className="relative flex-1 bg-violet-400">
              <MyImages
                src={greenLemon}
                className="w-full min-h-screen object-cover"
              />
            </div>

            <div className="flex-1 text-banana-400 flex flex-col items-center">
              <div className=" h-full flex flex-col justify-between">
                <div className="flex-1">
                  <p className="w-full pt-4">
                    Let's do good
                    <br />
                    together.
                  </p>
                </div>
                <h1 className="mx-auto text-banana-400 w-max mb-2 leading-14 text-offWhite text-6xl font-bold tracking-tighter">
                  Apeel gives the entire <br /> supply chain more <br /> time.
                  That's better for <br /> your business, your <br /> customers,
                  and our <br /> planet.
                </h1>
                <Link
                  href="/index"
                  className="mb-8 w-2/3 flex items-center text-sm text-left leading-5 font-semibold text-offWhite"
                >
                  <p className="text-banana-400">More about Retail.</p>{" "}
                  <Image src={svgLeft} width={30} />
                </Link>
              </div>
            </div>
          </div>
        </div>

        <div>
          <div>
            <h1>
              Step inside the wordl <br />
              of Apeel.
            </h1>
          </div>
          {/* slider images */}
          <div>{/* componenets gies here */}</div>
        </div>
      </main>
    </div>
  );
}
